# bucket

output "bucket_name" {
  description = "The name of the bucket."
  value       = module.storage_buckets.bucket_name
}

output "storage_admin_access_key" {
  description = "Static access key of the autogenerated Object storage admin service account."
  value       = module.storage_buckets.storage_admin_access_key
}

output "storage_admin_secret_key" {
  description = "Static secret key of the autogenerated Object storage admin service account."
  sensitive   = true
  value       = module.storage_buckets.storage_admin_secret_key
}

# Airflow cluster outputs
output "airflow_cluster_id" {
  description = "ID созданного кластера Airflow"
  value       = module.airflow.airflow_cluster_id
}

output "airflow_cluster_name" {
  description = "Имя созданного кластера Airflow"
  value       = module.airflow.airflow_cluster_name
}

output "airflow_cluster_status" {
  description = "Статус кластера Airflow"
  value       = module.airflow.airflow_cluster_status
}

# output "airflow_webserver_url" {
#   description = "URL веб-сервера Airflow"
#   value       = module.airflow.airflow_webserver_url
# }

output "airflow_service_account_id" {
  description = "ID сервисного аккаунта, используемого кластером Airflow"
  value       = module.airflow.airflow_service_account_id
}

output "airflow_subnet_ids" {
  description = "Список ID подсетей, используемых кластером Airflow"
  value       = module.airflow.airflow_subnet_ids
}

output "airflow_created_at" {
  description = "Время создания кластera Airflow"
  value       = module.airflow.airflow_created_at
}

output "airflow_health" {
  description = "Состояние здоровья кластера Airflow"
  value       = module.airflow.airflow_health
}

output "airflow_log_group_id" {
  description = "ID группы логов Cloud Logging для кластера Airflow"
  value       = module.airflow.airflow_log_group_id
}
